### PR TITLE
Cleanup and fixes

### PR DESCRIPTION
**Pull request by jjcarstens**
* Currently, this lib is only hardcoded to read `DHT22` sensors. So this changes that to use the passed in sensor identifier
* Fixes the genserver crashing when error is reported
* Also a few cleanup points and adding support for `rpi3a` and `rpi4`

### CODE REVIEW

**Comment by esdrasedu** [comment]
Thanks @jjcarstens

**Comment by s3vus** [comment]
is there a minor release for this PR a-comin'?  🤔

**Comment by esdrasedu** [comment]
@s3vus done, it is `0.1.1`!

**Comment by s3vus** [comment]
Woot!  🎉

**Pull request merged**
